name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: JustJoka
          outputs: dist/snake.svg

      - name: Push Snake
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
